import json
from pathlib import Path

from docx import Document
from sqlalchemy.orm import Session

from app.models.rfp import RFPDocument, RFPDraftExport, RFPDraftSection
from app.services.draft_quality_service import evaluate_draft_quality
from app.services.draft_validation_service import DraftNotReadyError, validate_draft_sections
from app.services.job_service import get_latest_generation_job
from app.utils.text_utils import count_words


def export_private_short_draft(db: Session, rfp_id: int) -> dict:
    rfp = db.get(RFPDocument, rfp_id)
    if rfp is None:
        raise ValueError("RFP document not found.")

    sections = db.query(RFPDraftSection).filter(RFPDraftSection.rfp_id == rfp_id).order_by(RFPDraftSection.section_order).all()
    if not sections:
        raise DraftNotReadyError()

    job = get_latest_generation_job(db, rfp_id)
    if job is None or job.status != "completed":
        raise DraftNotReadyError()

    is_valid, issues = validate_draft_sections(sections)
    if not is_valid:
        raise DraftNotReadyError("; ".join(issues) if issues else "Draft is not ready for export. Please complete generation first.")

    quality_report = evaluate_draft_quality(db, rfp_id)
    output_dir = Path("storage/exports")
    output_dir.mkdir(parents=True, exist_ok=True)
    file_name = f"rfp_{rfp_id}_private_short_draft.docx"
    file_path = output_dir / file_name

    document = Document()
    document.add_heading("Private Short RFP Response Draft", level=0)
    document.add_paragraph(f"Source RFP: {rfp.title or rfp.original_filename}")
    document.add_paragraph("Generated by Private RFP Tool")
    document.add_paragraph("Privacy note: Generated locally. No external AI provider used.")
    document.add_paragraph("Human review required before submission.")
    document.add_page_break()

    document.add_heading("Table of Contents", level=1)
    document.add_paragraph("Placeholder. Use Microsoft Word to update fields if a formal table of contents is required.")
    document.add_page_break()

    for section in sections:
        document.add_heading(section.section_title, level=1)
        _add_content(document, section.section_content)

    document.add_page_break()
    document.add_heading("Quality Report Appendix", level=1)
    document.add_paragraph(f"Overall status: {quality_report['overall_status']}")
    for check in quality_report["checks"]:
        document.add_paragraph(f"- {check['status']}: {check['message']}")

    document.save(file_path)

    total_words = sum(section.word_count for section in sections)
    export = RFPDraftExport(
        rfp_id=rfp_id,
        export_type="private_short_draft",
        file_path=str(file_path),
        file_name=file_name,
        page_estimate=max(1, round(total_words / 350)),
        word_count=total_words,
        quality_report_json=json.dumps(quality_report),
    )
    db.add(export)
    db.commit()
    db.refresh(export)

    return {
        "rfp_id": rfp_id,
        "export_id": export.id,
        "file_path": export.file_path,
        "file_name": export.file_name,
        "page_estimate": export.page_estimate,
        "word_count": export.word_count,
        "quality_report": quality_report,
        "external_api_used": False,
    }


def _add_content(document: Document, content: str) -> None:
    for block in content.splitlines():
        stripped = block.strip()
        if not stripped:
            continue
        if stripped.startswith("- "):
            document.add_paragraph(stripped[2:], style="List Bullet")
        else:
            document.add_paragraph(stripped)
